version: '3'
services:
  Ejercicio_1:
    image: bioperl-test
    command: bash -c "cd Ejercicio_1 && perl Ex1.pm NM_000311.5.gb NM_000311.5.fas"
    volumes:
      - ./Ejercicio_1:/usr/src/app/Ejercicio_1
  Ejercicio_2:
   image: bioperl-test
   command: bash -c "cd Ejercicio_2 && perl Ex2.pm NM_000311.5.fas NM_000311.5.blast.out"
   volumes:
     - ./Ejercicio_2:/usr/src/app/Ejercicio_2
  Ejercicio_4:
   image: bioperl-test
   command: bash -c "cd Ejercicio_4 && perl Ex4.pm MCT9STDR016_NM_000311.5.blast.out Macaca MCT9STDR016_NM_000311.5.blast.fas.out"
   volumes:
     - ./Ejercicio_4:/usr/src/app/Ejercicio_4
  Ejercicio_5:
    image: bioperl-test
    command: bash -c "prosextract /usr/src/app/Ejercicio_5 && cd Ejercicio_5 && perl Ex5.pm NM_000311.5.gb output_1 output_2"
    volumes:
      - ./Ejercicio_5:/usr/src/app/Ejercicio_5